## Exercise I

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data/YearPredictionMSD.csv", nrows=50000)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
0,2001,49.94357,21.47114,73.07750,8.74861,-17.40628,-13.09905,-25.01202,-12.23257,7.83089,...,13.01620,-54.40548,58.99367,15.37344,1.11144,-23.08793,68.40795,-1.82223,-27.46348,2.26327
1,2001,48.73215,18.42930,70.32679,12.94636,-10.32437,-24.83777,8.76630,-0.92019,18.76548,...,5.66812,-19.68073,33.04964,42.87836,-9.90378,-32.22788,70.49388,12.04941,58.43453,26.92061
2,2001,50.95714,31.85602,55.81851,13.41693,-6.57898,-18.54940,-3.27872,-2.35035,16.07017,...,3.03800,26.05866,-50.92779,10.93792,-0.07568,43.20130,-115.00698,-0.05859,39.67068,-0.66345
3,2001,48.24750,-1.89837,36.29772,2.58776,0.97170,-26.21683,5.05097,-10.34124,3.55005,...,34.57337,-171.70734,-16.96705,-46.67617,-12.51516,82.58061,-72.08993,9.90558,199.62971,18.85382
4,2001,50.97020,42.20998,67.09964,8.46791,-15.85279,-16.81409,-12.48207,-9.37636,12.63699,...,9.92661,-55.95724,64.92712,-17.72522,-1.49237,-7.50035,51.76631,7.88713,55.66926,28.74903

In [3]:
data.shape

(50000, 91)

In [4]:
outliers = {}
for i in range(data.shape[1]):
    min_t = data[data.columns[i]].mean() - (3 * data[data.columns[i]].std())
    max_t = data[data.columns[i]].mean() + (3 * data[data.columns[i]].std())
    count = 0
    for j in data[data.columns[i]]:
        if j < min_t or j > max_t:
            count += 1
    percentage = count/data.shape[0]
    outliers[data.columns[i]] = "%.3f" % percentage

print(outliers)

{'0': '0.019', '1': '0.010', '2': '0.011', '3': '0.011', '4': '0.015', '5': '0.008', '6': '0.010', '7': '0.010', '8': '0.010', '9': '0.011', '10': '0.005', '11': '0.010', '12': '0.010', '13': '0.015', '14': '0.017', '15': '0.016', '16': '0.016', '17': '0.014', '18': '0.016', '19': '0.013', '20': '0.016', '21': '0.015', '22': '0.013', '23': '0.015', '24': '0.013', '25': '0.018', '26': '0.017', '27': '0.017', '28': '0.018', '29': '0.017', '30': '0.016', '31': '0.015', '32': '0.017', '33': '0.016', '34': '0.015', '35': '0.016', '36': '0.017', '37': '0.017', '38': '0.016', '39': '0.015', '40': '0.017', '41': '0.017', '42': '0.015', '43': '0.014', '44': '0.016', '45': '0.015', '46': '0.017', '47': '0.017', '48': '0.017', '49': '0.015', '50': '0.016', '51': '0.015', '52': '0.015', '53': '0.015', '54': '0.016', '55': '0.018', '56': '0.017', '57': '0.016', '58': '0.013', '59': '0.016', '60': '0.016', '61': '0.015', '62': '0.016', '63': '0.017', '64': '0.017', '65': '0.016', '66': '0.018', '67': '0.015', '68': '0.018', '69': '0.016', '70': '0.017', '71': '0.016', '72': '0.018', '73': '0.015', '74': '0.016', '75': '0.015', '76': '0.017', '77': '0.018', '78': '0.015', '79': '0.014', '80': '0.015', '81': '0.018', '82': '0.017', '83': '0.015', '84': '0.016', '85': '0.015', '86': '0.016', '87': '0.015', '88': '0.015', '89': '0.017', '90': '0.018'}

In [5]:
# Data Rescaling

X = data.iloc[:,1:]
Y = data.iloc[:,0]

In [6]:
X = (X - X.mean())/X.std()
X.head()

,1,2,3,4,5,6,7,8,9,10,...,81,82,83,84,85,86,87,88,89,90
0,1.082657,0.382437,1.841985,0.459652,-0.480074,-0.282606,-1.590785,-1.300854,0.378336,-0.683719,...,-0.086005,0.099339,0.148291,-0.255625,0.040944,-0.362616,0.524542,-0.467668,-0.247579,0.036872
1,0.880874,0.321953,1.763666,0.717085,-0.165507,-1.188896,0.777905,0.122576,1.420531,0.401198,...,-0.316635,0.301448,-0.063611,0.031855,-0.655124,-0.443921,0.536517,0.573191,0.209887,1.155171
2,1.251484,0.588929,1.350579,0.745944,0.000857,-0.703401,-0.066747,-0.057380,1.163637,-0.090081,...,-0.399185,0.567666,-0.749508,-0.301984,-0.034072,0.227059,-0.528413,-0.335333,0.109957,-0.095865
3,0.800148,-0.082240,0.794774,0.081829,0.336246,-1.295366,0.517369,-1.062869,-0.029679,-1.282306,...,0.590596,-0.583396,-0.472129,-0.904164,-0.820141,0.577357,-0.282033,0.412329,0.961849,0.789313
4,1.253660,0.794806,1.671781,0.442438,-0.411071,-0.569426,-0.712128,-0.941459,0.836414,-0.160630,...,-0.182976,0.090307,0.196753,-0.601570,-0.123595,-0.223957,0.429005,0.260874,0.195160,1.238096

In [7]:
# Splitting the Dataset

from sklearn.model_selection import train_test_split

X_shuffle = X.sample(frac=1, random_state=0)
Y_shuffle = Y.sample(frac=1, random_state=0)

x_new, x_test, y_new, y_test = train_test_split(X_shuffle, Y_shuffle, test_size=0.2, random_state=0)
dev_per = x_test.shape[0]/x_new.shape[0]
x_train, x_dev, y_train, y_dev = train_test_split(x_new, y_new, test_size=dev_per, random_state=0)

print(x_train.shape, y_train.shape)
print(x_dev.shape, y_dev.shape)
print(x_test.shape, y_test.shape)

(30000, 90) (30000,)
(10000, 90) (10000,)
(10000, 90) (10000,)

In [8]:
import torch
import torch.nn as nn

In [9]:
torch.manual_seed(0)

In [10]:
x_train = torch.tensor(x_train.values).float()
y_train = torch.tensor(y_train.values).float()

x_dev = torch.tensor(x_dev.values).float()
y_dev = torch.tensor(y_dev.values).float()

x_test = torch.tensor(x_test.values).float()
y_test = torch.tensor(y_test.values).float()

In [11]:
model = nn.Sequential(nn.Linear(x_train.shape[1],10),
                      nn.ReLU(),
                      
                      nn.Linear(10,7),
                      nn.ReLU(),
                      
                      nn.Linear(7,5),
                      nn.ReLU(),
                     
                      nn.Linear(5,1))

In [12]:
loss_function = torch.nn.MSELoss()

In [13]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [14]:
for i in range(3000):
    y_pred = model(x_train).squeeze()
    loss = loss_function(y_pred, y_train)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if i%250 == 0:
        print(i, loss.item())

0 3994019.0
250 201388.40625
500 14110.4970703125
750 1335.8421630859375
1000 395.6597900390625
1250 194.93479919433594
1500 133.73922729492188
1750 110.15499114990234
2000 100.0080337524414
2250 95.13744354248047
2500 92.4844970703125
2750 90.95288848876953

In [15]:
pred = model(x_test[0])
print("Ground truth:", y_test[0].item(), "Prediction:", pred.item())

Ground truth: 1995.0 Prediction: 1998.0126953125

In [16]:
pred

tensor([1998.0127], grad_fn=<AddBackward0>)

## Exercise II

In [18]:
data = pd.read_csv("data/energydata_complete.csv")
data = data.drop(columns=["date"])
data.head()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [19]:
data.isnull().sum()

Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [20]:
outliers = {}
for i in range(data.shape[1]):
    min_t = data[data.columns[i]].mean() - (3 * data[data.columns[i]].std())
    max_t = data[data.columns[i]].mean() + (3 * data[data.columns[i]].std())
    count = 0
    for j in data[data.columns[i]]:
        if j < min_t or j > max_t:
            count += 1
    percentage = count/data.shape[0]
    outliers[data.columns[i]] = "%.3f" % percentage

outliers

{'Appliances': '0.027',
 'lights': '0.033',
 'T1': '0.001',
 'RH_1': '0.006',
 'T2': '0.010',
 'RH_2': '0.007',
 'T3': '0.003',
 'RH_3': '0.001',
 'T4': '0.000',
 'RH_4': '0.000',
 'T5': '0.001',
 'RH_5': '0.029',
 'T6': '0.005',
 'RH_6': '0.000',
 'T7': '0.000',
 'RH_7': '0.001',
 'T8': '0.000',
 'RH_8': '0.000',
 'T9': '0.000',
 'RH_9': '0.000',
 'T_out': '0.005',
 'Press_mm_hg': '0.005',
 'RH_out': '0.008',
 'Windspeed': '0.005',
 'Visibility': '0.002',
 'Tdewpoint': '0.000',
 'rv1': '0.000',
 'rv2': '0.000'}

In [21]:
X = data.iloc[:,1:]
Y = data.iloc[:,0]

X = (X - X.min())/(X.max() - X.min())
X.head()

,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.428571,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.428571,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.428571,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.571429,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.571429,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [22]:
X.shape

(19735, 27)

In [23]:
train_end = int(len(X) * 0.6)
dev_end = int(len(X) * 0.8)

In [24]:
X_shuffle = X.sample(frac=1, random_state=0)
Y_shuffle = Y.sample(frac=1, random_state=0)

In [25]:
x_train = X_shuffle.iloc[:train_end,:]
y_train = Y_shuffle.iloc[:train_end]
x_dev = X_shuffle.iloc[train_end:dev_end,:]
y_dev = Y_shuffle.iloc[train_end:dev_end]
x_test = X_shuffle.iloc[dev_end:,:]
y_test = Y_shuffle.iloc[dev_end:]

In [26]:
print(x_train.shape, y_train.shape)
print(x_dev.shape, y_dev.shape)
print(x_test.shape, y_test.shape)

(11841, 27) (11841,)
(3947, 27) (3947,)
(3947, 27) (3947,)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_new, x_test_2, y_new, y_test_2 = train_test_split(X_shuffle, Y_shuffle, test_size=0.2, random_state=0)
dev_per = x_test_2.shape[0]/x_new.shape[0]
x_train_2, x_dev_2, y_train_2, y_dev_2 = train_test_split(x_new, y_new, test_size=dev_per, random_state=0)

In [29]:
print(x_train_2.shape, y_train_2.shape)
print(x_dev_2.shape, y_dev_2.shape)
print(x_test_2.shape, y_test_2.shape)

(11841, 27) (11841,)
(3947, 27) (3947,)
(3947, 27) (3947,)

In [30]:
import torch
import torch.nn as nn

In [31]:
x_train = torch.tensor(x_train.values).float()
y_train = torch.tensor(y_train.values).float()

x_dev = torch.tensor(x_dev.values).float()
y_dev = torch.tensor(y_dev.values).float()

x_test = torch.tensor(x_test.values).float()
y_test = torch.tensor(y_test.values).float()

In [32]:
model = nn.Sequential(nn.Linear(x_train.shape[1],100),
                      nn.ReLU(),
                      
                      nn.Linear(100,50),
                      nn.ReLU(),
                      
                      nn.Linear(50,25),
                      nn.ReLU(),
                     
                      nn.Linear(25,1))

In [33]:
loss_function = torch.nn.MSELoss()

In [34]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [35]:
for i in range(1000):
    y_pred = model(x_train).squeeze()
    loss = loss_function(y_pred, y_train)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if i%100 == 0:
        print(i, loss.item())

0 20344.22265625
100 10977.9609375
200 10754.70703125
300 10592.19921875
400 10293.6513671875
500 9856.96875
600 9505.95703125
700 9300.6142578125
800 9103.328125
900 8892.1455078125

In [36]:
pred = model(x_test[0])
print("Ground truth:", y_test[0].item(), "Prediction:",pred.item())

Ground truth: 60.0 Prediction: 56.99934387207031